# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170213_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='img_path',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='intrinsic_matrix',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
