# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20170219_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='altitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]