# Generated by Django 2.0.4 on 2018-04-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_marker_interop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='img_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='intrinsic_matrix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
