# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tagger.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1730, 1250)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1721, 1171))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_setup = QtGui.QWidget()
        self.tab_setup.setObjectName(_fromUtf8("tab_setup"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_setup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 634, 156))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_sessionDirectory = QtGui.QLineEdit(self.groupBox)
        self.line_sessionDirectory.setObjectName(_fromUtf8("line_sessionDirectory"))
        self.gridLayout.addWidget(self.line_sessionDirectory, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.button_sessionDirectory = QtGui.QPushButton(self.groupBox)
        self.button_sessionDirectory.setObjectName(_fromUtf8("button_sessionDirectory"))
        self.gridLayout.addWidget(self.button_sessionDirectory, 2, 2, 1, 1)
        self.line_sessionName = QtGui.QLineEdit(self.groupBox)
        self.line_sessionName.setObjectName(_fromUtf8("line_sessionName"))
        self.gridLayout.addWidget(self.line_sessionName, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_setup, _fromUtf8(""))
        self.tab_tagging = QtGui.QWidget()
        self.tab_tagging.setObjectName(_fromUtf8("tab_tagging"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_tagging)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.layout_tagging = QtGui.QHBoxLayout()
        self.layout_tagging.setObjectName(_fromUtf8("layout_tagging"))
        self.layout_taggingControls = QtGui.QVBoxLayout()
        self.layout_taggingControls.setObjectName(_fromUtf8("layout_taggingControls"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_tagging)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_2.addWidget(self.listWidget)
        self.layout_tagsButtons = QtGui.QHBoxLayout()
        self.layout_tagsButtons.setObjectName(_fromUtf8("layout_tagsButtons"))
        self.button_addTag = QtGui.QPushButton(self.groupBox_2)
        self.button_addTag.setObjectName(_fromUtf8("button_addTag"))
        self.layout_tagsButtons.addWidget(self.button_addTag)
        self.button_editTag = QtGui.QPushButton(self.groupBox_2)
        self.button_editTag.setObjectName(_fromUtf8("button_editTag"))
        self.layout_tagsButtons.addWidget(self.button_editTag)
        self.button_removeTag = QtGui.QPushButton(self.groupBox_2)
        self.button_removeTag.setObjectName(_fromUtf8("button_removeTag"))
        self.layout_tagsButtons.addWidget(self.button_removeTag)
        self.verticalLayout_2.addLayout(self.layout_tagsButtons)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_3)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 3)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.listWidget.raise_()
        self.groupBox_3.raise_()
        self.layout_taggingControls.addWidget(self.groupBox_2)
        self.label_5 = QtGui.QLabel(self.tab_tagging)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layout_taggingControls.addWidget(self.label_5)
        self.layout_tagging.addLayout(self.layout_taggingControls)
        self.layout_taggingImage = QtGui.QVBoxLayout()
        self.layout_taggingImage.setObjectName(_fromUtf8("layout_taggingImage"))
        self.label_3 = QtGui.QLabel(self.tab_tagging)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8("../../Desktop/Desktop/20160430_111051_217148.jpg")))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layout_taggingImage.addWidget(self.label_3)
        self.layout_tagging.addLayout(self.layout_taggingImage)
        self.layout_tagging.setStretch(0, 1)
        self.layout_tagging.setStretch(1, 3)
        self.horizontalLayout_3.addLayout(self.layout_tagging)
        self.tabWidget.addTab(self.tab_tagging, _fromUtf8(""))
        self.tab_targets = QtGui.QWidget()
        self.tab_targets.setObjectName(_fromUtf8("tab_targets"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tab_targets)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(6, 7, 1701, 1101))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.horizontalLayoutWidget_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.listView_2 = QtGui.QListView(self.groupBox_5)
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.verticalLayout_6.addWidget(self.listView_2)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_4 = QtGui.QGroupBox(self.horizontalLayoutWidget_5)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.listView = QtGui.QListView(self.groupBox_4)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout_5.addWidget(self.listView)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.tabWidget.addTab(self.tab_targets, _fromUtf8(""))
        self.tab_map = QtGui.QWidget()
        self.tab_map.setObjectName(_fromUtf8("tab_map"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_map)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 1521, 891))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.gridLayoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.listWidget_3 = QtGui.QListWidget(self.groupBox_6)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.verticalLayout_7.addWidget(self.listWidget_3)
        self.listWidget_3.raise_()
        self.gridLayout_3.addWidget(self.groupBox_6, 2, 0, 1, 3)
        self.lineEdit_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(3, 3)
        self.tabWidget.addTab(self.tab_map, _fromUtf8(""))
        self.tabWidget.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1730, 43))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuTest.addAction(self.actionQuit)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Team Guardian Image Tagger", None))
        self.groupBox.setTitle(_translate("MainWindow", "Session", None))
        self.label.setText(_translate("MainWindow", "Working Directory:", None))
        self.label_2.setText(_translate("MainWindow", "Name:", None))
        self.button_sessionDirectory.setText(_translate("MainWindow", "Browse...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("MainWindow", "Setup", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tags", None))
        self.button_addTag.setText(_translate("MainWindow", "Add", None))
        self.button_editTag.setText(_translate("MainWindow", "Edit", None))
        self.button_removeTag.setText(_translate("MainWindow", "Remove", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Images", None))
        self.pushButton_3.setText(_translate("MainWindow", "Mark as Reviewed", None))
        self.pushButton_6.setText(_translate("MainWindow", "Next", None))
        self.pushButton_4.setText(_translate("MainWindow", "Fit to Screen", None))
        self.pushButton_5.setText(_translate("MainWindow", "Previous", None))
        self.pushButton_7.setText(_translate("MainWindow", "Toggle View", None))
        self.label_5.setText(_translate("MainWindow", "MINIMAP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tagging), _translate("MainWindow", "Tagging", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select Tag", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Images with Selected Tag", None))
        self.lineEdit.setText(_translate("MainWindow", "search image by name", None))
        self.label_6.setText(_translate("MainWindow", "MINIMAP", None))
        self.label_4.setText(_translate("MainWindow", "IMAGE VIEW", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_targets), _translate("MainWindow", "Targets", None))
        self.pushButton_8.setText(_translate("MainWindow", "Search", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox", None))
        self.label_8.setText(_translate("MainWindow", "MAP VIEW", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map), _translate("MainWindow", "Map", None))
        self.menuTest.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Exit", None))

