# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tagger.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_setup)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.layout_setup = QtWidgets.QHBoxLayout()
        self.layout_setup.setObjectName("layout_setup")
        self.groupBox = QtWidgets.QGroupBox(self.tab_setup)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_sessionDirectory = QtWidgets.QLineEdit(self.groupBox)
        self.line_sessionDirectory.setObjectName("line_sessionDirectory")
        self.gridLayout.addWidget(self.line_sessionDirectory, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.button_sessionDirectory = QtWidgets.QPushButton(self.groupBox)
        self.button_sessionDirectory.setObjectName("button_sessionDirectory")
        self.gridLayout.addWidget(self.button_sessionDirectory, 2, 2, 1, 1)
        self.line_sessionName = QtWidgets.QLineEdit(self.groupBox)
        self.line_sessionName.setObjectName("line_sessionName")
        self.gridLayout.addWidget(self.line_sessionName, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.layout_setup.addWidget(self.groupBox)
        self.verticalLayout_9.addLayout(self.layout_setup)
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_tagging = QtWidgets.QWidget()
        self.tab_tagging.setObjectName("tab_tagging")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_tagging)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_tagging = QtWidgets.QHBoxLayout()
        self.layout_tagging.setObjectName("layout_tagging")
        self.layout_taggingControls = QtWidgets.QVBoxLayout()
        self.layout_taggingControls.setObjectName("layout_taggingControls")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_tagging)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_tags = QtWidgets.QListWidget(self.groupBox_2)
        self.list_tags.setMaximumSize(QtCore.QSize(16777215, 150))
        self.list_tags.setObjectName("list_tags")
        self.verticalLayout_2.addWidget(self.list_tags)
        self.layout_tagsButtons = QtWidgets.QHBoxLayout()
        self.layout_tagsButtons.setObjectName("layout_tagsButtons")
        self.button_addTag = QtWidgets.QPushButton(self.groupBox_2)
        self.button_addTag.setObjectName("button_addTag")
        self.layout_tagsButtons.addWidget(self.button_addTag)
        self.button_editTag = QtWidgets.QPushButton(self.groupBox_2)
        self.button_editTag.setObjectName("button_editTag")
        self.layout_tagsButtons.addWidget(self.button_editTag)
        self.button_removeTag = QtWidgets.QPushButton(self.groupBox_2)
        self.button_removeTag.setObjectName("button_removeTag")
        self.layout_tagsButtons.addWidget(self.button_removeTag)
        self.verticalLayout_2.addLayout(self.layout_tagsButtons)
        self.layout_taggingControls.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_tagging)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_images = QtWidgets.QListWidget(self.groupBox_3)
        self.list_images.setObjectName("list_images")
        self.verticalLayout_3.addWidget(self.list_images)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_toggleReviewed = QtWidgets.QPushButton(self.groupBox_3)
        self.button_toggleReviewed.setObjectName("button_toggleReviewed")
        self.gridLayout_2.addWidget(self.button_toggleReviewed, 0, 0, 1, 3)
        self.button_next = QtWidgets.QPushButton(self.groupBox_3)
        self.button_next.setObjectName("button_next")
        self.gridLayout_2.addWidget(self.button_next, 1, 2, 1, 1)
        self.button_fitScreen = QtWidgets.QPushButton(self.groupBox_3)
        self.button_fitScreen.setObjectName("button_fitScreen")
        self.gridLayout_2.addWidget(self.button_fitScreen, 2, 2, 1, 1)
        self.button_previous = QtWidgets.QPushButton(self.groupBox_3)
        self.button_previous.setObjectName("button_previous")
        self.gridLayout_2.addWidget(self.button_previous, 1, 0, 1, 1)
        self.button_toggleView = QtWidgets.QPushButton(self.groupBox_3)
        self.button_toggleView.setObjectName("button_toggleView")
        self.gridLayout_2.addWidget(self.button_toggleView, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(0, 150))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.layout_taggingControls.addWidget(self.groupBox_3)
        self.layout_tagging.addLayout(self.layout_taggingControls)
        self.layout_taggingImage = QtWidgets.QVBoxLayout()
        self.layout_taggingImage.setObjectName("layout_taggingImage")
        self.viewer_single = PhotoViewer(self.tab_tagging)
        self.viewer_single.setObjectName("viewer_single")
        self.layout_taggingImage.addWidget(self.viewer_single)
        self.layout_tagging.addLayout(self.layout_taggingImage)
        self.layout_tagging.setStretch(0, 1)
        self.layout_tagging.setStretch(1, 3)
        self.horizontalLayout_3.addLayout(self.layout_tagging)
        self.tabWidget.addTab(self.tab_tagging, "")
        self.tab_targets = QtWidgets.QWidget()
        self.tab_targets.setObjectName("tab_targets")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_targets)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_targets = QtWidgets.QHBoxLayout()
        self.layout_targets.setContentsMargins(-1, -1, 0, -1)
        self.layout_targets.setObjectName("layout_targets")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_targets)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.list_tagFilter = QtWidgets.QListView(self.groupBox_5)
        self.list_tagFilter.setObjectName("list_tagFilter")
        self.verticalLayout_6.addWidget(self.list_tagFilter)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_targets)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.list_taggedImages = QtWidgets.QListView(self.groupBox_4)
        self.list_taggedImages.setObjectName("list_taggedImages")
        self.verticalLayout_5.addWidget(self.list_taggedImages)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.label_6 = QtWidgets.QLabel(self.tab_targets)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.layout_targets.addLayout(self.verticalLayout_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.viewer_targets = PhotoViewer(self.tab_targets)
        self.viewer_targets.setObjectName("viewer_targets")
        self.verticalLayout_10.addWidget(self.viewer_targets)
        self.layout_targets.addLayout(self.verticalLayout_10)
        self.layout_targets.setStretch(0, 1)
        self.layout_targets.setStretch(1, 3)
        self.horizontalLayout.addLayout(self.layout_targets)
        self.viewer_targets.raise_()
        self.tabWidget.addTab(self.tab_targets, "")
        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_map)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout_map = QtWidgets.QHBoxLayout()
        self.layout_map.setContentsMargins(0, -1, -1, -1)
        self.layout_map.setObjectName("layout_map")
        self.layout_allImages = QtWidgets.QVBoxLayout()
        self.layout_allImages.setContentsMargins(0, 0, -1, -1)
        self.layout_allImages.setObjectName("layout_allImages")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_map)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_map)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_map)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.layout_allImages.addLayout(self.horizontalLayout_2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_map)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.list_allImages = QtWidgets.QListWidget(self.groupBox_6)
        self.list_allImages.setObjectName("list_allImages")
        self.verticalLayout_7.addWidget(self.list_allImages)
        self.layout_allImages.addWidget(self.groupBox_6)
        self.layout_map.addLayout(self.layout_allImages)
        self.viewer_map = PhotoViewer(self.tab_map)
        self.viewer_map.setObjectName("viewer_map")
        self.layout_map.addWidget(self.viewer_map)
        self.layout_map.setStretch(0, 1)
        self.layout_map.setStretch(1, 3)
        self.verticalLayout_8.addLayout(self.layout_map)
        self.tabWidget.addTab(self.tab_map, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 43))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuTest.addAction(self.actionQuit)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Team Guardian Image Tagger"))
        self.groupBox.setTitle(_translate("MainWindow", "Session"))
        self.label.setText(_translate("MainWindow", "Working Directory:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.button_sessionDirectory.setText(_translate("MainWindow", "Browse..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Tags"))
        self.button_addTag.setText(_translate("MainWindow", "Add"))
        self.button_editTag.setText(_translate("MainWindow", "Edit"))
        self.button_removeTag.setText(_translate("MainWindow", "Remove"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Images"))
        self.button_toggleReviewed.setText(_translate("MainWindow", "Mark as Reviewed"))
        self.button_next.setText(_translate("MainWindow", "Next"))
        self.button_fitScreen.setText(_translate("MainWindow", "Fit to Screen"))
        self.button_previous.setText(_translate("MainWindow", "Previous"))
        self.button_toggleView.setText(_translate("MainWindow", "Toggle View"))
        self.label_5.setText(_translate("MainWindow", "MINIMAP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tagging), _translate("MainWindow", "Tagging"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Select Tag"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Images with Selected Tag"))
        self.lineEdit.setText(_translate("MainWindow", "search image by name"))
        self.label_6.setText(_translate("MainWindow", "MINIMAP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_targets), _translate("MainWindow", "Targets"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "latitude"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "longitude"))
        self.pushButton_8.setText(_translate("MainWindow", "Search"))
        self.groupBox_6.setTitle(_translate("MainWindow", "List of Images"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_map), _translate("MainWindow", "Map"))
        self.menuTest.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Exit"))

from photoViewer import PhotoViewer
