# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interopTarget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1000, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(640, 450, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 971, 441))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_targetType = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_targetType.setObjectName("label_targetType")
        self.horizontalLayout_5.addWidget(self.label_targetType)
        self.comboBox_targetType = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_targetType.setObjectName("comboBox_targetType")
        self.horizontalLayout_5.addWidget(self.comboBox_targetType)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_shape = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_shape.setObjectName("label_shape")
        self.horizontalLayout_4.addWidget(self.label_shape)
        self.comboBox_shape = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_shape.setObjectName("comboBox_shape")
        self.horizontalLayout_4.addWidget(self.comboBox_shape)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_shapeColor = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_shapeColor.setObjectName("label_shapeColor")
        self.horizontalLayout_3.addWidget(self.label_shapeColor)
        self.comboBox_shapeColor = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_shapeColor.setObjectName("comboBox_shapeColor")
        self.horizontalLayout_3.addWidget(self.comboBox_shapeColor)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_alphanumeric = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_alphanumeric.setObjectName("label_alphanumeric")
        self.horizontalLayout.addWidget(self.label_alphanumeric)
        self.lineEdit_alphanumeric = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_alphanumeric.setMaxLength(1)
        self.lineEdit_alphanumeric.setFrame(True)
        self.lineEdit_alphanumeric.setObjectName("lineEdit_alphanumeric")
        self.horizontalLayout.addWidget(self.lineEdit_alphanumeric)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_alphanumericColor = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_alphanumericColor.setObjectName("label_alphanumericColor")
        self.horizontalLayout_2.addWidget(self.label_alphanumericColor)
        self.comboBox_alphanumericColor = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_alphanumericColor.setObjectName("comboBox_alphanumericColor")
        self.horizontalLayout_2.addWidget(self.comboBox_alphanumericColor)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_orientation = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_orientation.setObjectName("label_orientation")
        self.horizontalLayout_11.addWidget(self.label_orientation)
        self.lineEdit_orientation = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_orientation.setEnabled(False)
        self.lineEdit_orientation.setObjectName("lineEdit_orientation")
        self.horizontalLayout_11.addWidget(self.lineEdit_orientation)
        self.pushButton_orientation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_orientation.setObjectName("pushButton_orientation")
        self.horizontalLayout_11.addWidget(self.pushButton_orientation)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 3)
        self.horizontalLayout_11.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_latitude = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_latitude.setObjectName("label_latitude")
        self.horizontalLayout_8.addWidget(self.label_latitude)
        self.lineEdit_latitude = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_latitude.setEnabled(False)
        self.lineEdit_latitude.setObjectName("lineEdit_latitude")
        self.horizontalLayout_8.addWidget(self.lineEdit_latitude)
        self.label_longitude = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_longitude.setObjectName("label_longitude")
        self.horizontalLayout_8.addWidget(self.label_longitude)
        self.lineEdit_longitude = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_longitude.setEnabled(False)
        self.lineEdit_longitude.setObjectName("lineEdit_longitude")
        self.horizontalLayout_8.addWidget(self.lineEdit_longitude)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.horizontalLayout_8.setStretch(2, 1)
        self.horizontalLayout_8.setStretch(3, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_hint = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_hint.sizePolicy().hasHeightForWidth())
        self.label_hint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_hint.setFont(font)
        self.label_hint.setObjectName("label_hint")
        self.horizontalLayout_13.addWidget(self.label_hint)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.setStretch(0, 4)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_description = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout_6.addWidget(self.label_description)
        self.lineEdit_description = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_description.setEnabled(False)
        self.lineEdit_description.setText("")
        self.lineEdit_description.setPlaceholderText("")
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.horizontalLayout_6.addWidget(self.lineEdit_description)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.button_cropTarget = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_cropTarget.setObjectName("button_cropTarget")
        self.horizontalLayout_7.addWidget(self.button_cropTarget)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 2)
        self.verticalLayout.setStretch(6, 2)
        self.verticalLayout.setStretch(7, 2)
        self.verticalLayout.setStretch(8, 2)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.viewer_target = TargetViewer(self.horizontalLayoutWidget)
        self.viewer_target.setObjectName("viewer_target")
        self.horizontalLayout_9.addWidget(self.viewer_target)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_targetType.setText(_translate("Dialog", "Target type"))
        self.label_shape.setText(_translate("Dialog", "Shape"))
        self.label_shapeColor.setText(_translate("Dialog", "Shape color"))
        self.label_alphanumeric.setText(_translate("Dialog", "Alphanumeric"))
        self.lineEdit_alphanumeric.setPlaceholderText(_translate("Dialog", "a-z 0-9 A-Z"))
        self.label_alphanumericColor.setText(_translate("Dialog", "Alphanumeric color"))
        self.label_orientation.setText(_translate("Dialog", "Orientation"))
        self.pushButton_orientation.setText(_translate("Dialog", "Draw"))
        self.label_latitude.setText(_translate("Dialog", "Latitude"))
        self.label_longitude.setText(_translate("Dialog", "Longitude"))
        self.label_hint.setText(_translate("Dialog", "Double-click on the textbox to edit"))
        self.label_description.setText(_translate("Dialog", "Description"))
        self.button_cropTarget.setText(_translate("Dialog", "Crop Target Image"))

from gui.targetViewer import TargetViewer
