# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interopTarget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_targetType = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_targetType.setObjectName("label_targetType")
        self.horizontalLayout_5.addWidget(self.label_targetType)
        self.comboBox_targetType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_targetType.setObjectName("comboBox_targetType")
        self.horizontalLayout_5.addWidget(self.comboBox_targetType)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_shape = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_shape.setObjectName("label_shape")
        self.horizontalLayout_4.addWidget(self.label_shape)
        self.comboBox_shape = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_shape.setObjectName("comboBox_shape")
        self.horizontalLayout_4.addWidget(self.comboBox_shape)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_shapeColor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_shapeColor.setObjectName("label_shapeColor")
        self.horizontalLayout_3.addWidget(self.label_shapeColor)
        self.comboBox_shapeColor = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_shapeColor.setObjectName("comboBox_shapeColor")
        self.horizontalLayout_3.addWidget(self.comboBox_shapeColor)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_alphanumeric = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_alphanumeric.setObjectName("label_alphanumeric")
        self.horizontalLayout.addWidget(self.label_alphanumeric)
        self.lineEdit_alphanumeric = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_alphanumeric.setObjectName("lineEdit_alphanumeric")
        self.horizontalLayout.addWidget(self.lineEdit_alphanumeric)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_alphanumericColor = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_alphanumericColor.setObjectName("label_alphanumericColor")
        self.horizontalLayout_2.addWidget(self.label_alphanumericColor)
        self.comboBox_alphanumericColor = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_alphanumericColor.setObjectName("comboBox_alphanumericColor")
        self.horizontalLayout_2.addWidget(self.comboBox_alphanumericColor)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_description = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout_6.addWidget(self.label_description)
        self.lineEdit_description = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_description.setText("")
        self.lineEdit_description.setPlaceholderText("")
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.horizontalLayout_6.addWidget(self.lineEdit_description)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.buttonBox.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_targetType.setText(_translate("Dialog", "Target type"))
        self.label_shape.setText(_translate("Dialog", "Shape"))
        self.label_shapeColor.setText(_translate("Dialog", "Shape color"))
        self.label_alphanumeric.setText(_translate("Dialog", "Alphanumeric"))
        self.lineEdit_alphanumeric.setPlaceholderText(_translate("Dialog", "a-z 0-9 A-Z"))
        self.label_alphanumericColor.setText(_translate("Dialog", "Alphanumeric color"))
        self.label_description.setText(_translate("Dialog", "Description"))

